---
- name: Install Docker on Azure VM
  hosts: ovh_vps
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    
    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - 'distribution'
    
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    
    - name: Update apt cache after adding Docker repository
      apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
    
    - name: Show Docker version
      debug:
        var: docker_version.stdout

    - name: Remove existing src directory
      file:
        path: ./src
        state: absent
        force: yes

    - name: Clone git repository
      git:
        repo: 'https://github.com/RanylFoumbi/Lxp-devops.git'
        dest: ./src
        version: 'main'
        force: yes

    - name: Create .env file from template
      template:
        src: ./templates/env.j2
        dest: ./src/.env
      vars:
        db: "{{ db }}"
        db_user: "{{ db_user }}"
        db_password: "{{ db_password }}"